[project]
name = "qmt-agent-trader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "cnequity==0.7.3",
    "openai-agents>=0.20.0",
    "tomlkit>=0.15.1",
]

[project.scripts]
qmt-agent = "qmt_agent.__main__:entrypoint"

[build-system]
requires = ["uv_build>=0.12.3,<0.13"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "qmt_agent"
